version: "3.8"

services:
  patient-postgres:
    image: postgres:15
    container_name: patient-postgres
    environment:
      POSTGRES_DB: patientdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
